### ISSUE TITLE
SyntaxError: <projectPATH>\react-share-linkedin\src\ShareLinkedin.js: Unexpected token (59:6)

### ISSUE THREAD

**Issue by pallas-als** [itarverne/react-share-linkedin#1]
Failed to compile error in create-react-app project as shown below:

SyntaxError: <projectPATH>\react-share-linkedin\src\ShareLinkedin.js: Unexpected token (59:6)

return (
> 59 |       <div style={linkedinWithParam}>
     |       ^
  60 |         <a href="#" rel="noopener" style={linkedin__link}
  61 |            onClick={handleClick} >
  62 |          <span style={linkedin__logo}>IN</span>

**Comment by general03** [comment]
Can you show me how to build your react app ?

**Comment by pallas-als** [comment]
I use npm start with react-scripts 2.1.5. What type of detail do you need?

**Comment by general03** [comment]
Can you put your link project and give the command to build and run project

Thanks
